#lang racket
(define (pascal-tri-element row col)
  (cond ((= col 1) 1)
        ((= row col) 1)
        (else (+ (pascal-tri-element (- row 1) (- col 1))
                 (pascal-tri-element (- row 1) col)
                 )
              )
        )
  )

(pascal-tri-element 1 1)
(pascal-tri-element 2 1)
(pascal-tri-element 2 2)
(pascal-tri-element 3 1)
(pascal-tri-element 3 2)
(pascal-tri-element 3 3)
(pascal-tri-element 4 3)
(pascal-tri-element 5 2)
(pascal-tri-element 5 3)