#lang racket
(define (make-account balance secret-password)
  (define call-the-cops "call the cops")
  (define times 0)
  (define (withdraw amount)  
    ((if (>= balance amount)
         (begin (set! balance (- balance amount))
                balance)
         "Insufficient funds")))
  (define (deposit amount)    
    ((set! balance (+ balance amount))
     balance))
  (define (dispatch m pwd)
    (if (eq? pwd secret-password)
        (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unkown request -- MAKE-ACCOUNT" m)))
        (if (>= times 7)
            call-the-cops
            (begin (set! times (+ times 1))
                   "Incorrect password"))))
  dispatch)

(define acc (make-account 100 'secret-password))

(acc 'withdraw 's)
(acc 'withdraw 's)
(acc 'withdraw 's)
(acc 'withdraw 's)
(acc 'withdraw 's)