#lang racket
(define (make-account balance secret-password)
  (define (withdraw amount)  
    ((if (>= balance amount)
         (begin (set! balance (- balance amount))
                balance)
         "Insufficient funds")))
  (define (deposit amount)    
    ((set! balance (+ balance amount))
     balance))
  (define (dispatch m pwd)
    (if (eq? pwd secret-password)
        (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unkown request -- MAKE-ACCOUNT" m)))
        "Incorrect password"))
  dispatch)

(define acc (make-account 100 'secret-password))

(acc 'withdraw 's)